databases:
  - name: taskmanager-db
    databaseName: taskmanager
    user: taskmanager
    region: oregon

services:
  - type: web
    name: taskmanager-app
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: FLASK_ENV
        value: production